version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7173:80"
        # Enter your local machine ip here
        # Temporary solution
        extra_hosts: 
          - "localhost:192.168.56.1"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "D0ckerDBPass"
            ACCEPT_EULA: "Y"